# -*- coding: utf-8 -*-
"""ComparandoGraficos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QX8WyEpN5s1d5gOBIuRpaiuyOn0ofxsM
"""

import matplotlib.pyplot as plt

x1 = [1,2, 3, 4, 5]
y1 = [2,3, 7, 1, 0]

x2 = [2, 4, 6, 8, 10]
y2 = [5, 1, 3, 7, 4]


titulo = "Gráfico de Barras 2"
eixox = "Eixo X"
eixoy = "Eixo Y"



# Legendas
plt.title(titulo)
plt.xlabel(eixox)
plt.ylabel(eixoy)

plt.bar(x1, y1, label = "Grupo 1")
plt.bar(x2, y2, label = "Grupo 2")
plt.legend()

plt.show()