# -*- coding: utf-8 -*-
"""graficosemlinhas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QX8WyEpN5s1d5gOBIuRpaiuyOn0ofxsM
"""

import matplotlib.pyplot as plt

x = [1,2]
y = [2,3]

plt.plot(x, y)
plt.show()