# -*- coding: utf-8 -*-
"""LegendasEmGraficos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QX8WyEpN5s1d5gOBIuRpaiuyOn0ofxsM
"""

import matplotlib.pyplot as plt

x = [1,2, 5]
y = [2,3, 7]

#Titulo

plt.title("Meu primeiro gráfico em Phyton")

#Eixos
plt.xlabel("Eixo X")
plt.ylabel("Eixo Y")

plt.plot(x, y)
plt.show()